// <auto-generated />
using System;
using AprendaMais.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AprendaMais.Migrations
{
    [DbContext(typeof(AprendaMaisContext))]
    [Migration("20200705171848_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AprendaMais.Model.AlternativaPergunta", b =>
                {
                    b.Property<int>("ID_pergunta")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_pergunta")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("A")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("B")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("C")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("D")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("E")
                        .HasColumnType("varchar(max)");

                    b.Property<int>("ID_alternativa")
                        .HasColumnName("id_alternativaprova")
                        .HasColumnType("int");

                    b.Property<string>("Resp_correto")
                        .IsRequired()
                        .HasColumnName("resp_certa")
                        .HasColumnType("varchar(1)");

                    b.Property<byte[]>("figura_A")
                        .HasColumnType("figure");

                    b.Property<byte[]>("figura_B")
                        .HasColumnType("figure");

                    b.Property<byte[]>("figura_C")
                        .HasColumnType("figure");

                    b.Property<byte[]>("figura_D")
                        .HasColumnType("figure");

                    b.Property<byte[]>("figura_E")
                        .HasColumnType("figure");

                    b.HasKey("ID_pergunta");

                    b.ToTable("alternativaprova");
                });

            modelBuilder.Entity("AprendaMais.Model.AvaliacaoAluno", b =>
                {
                    b.Property<int>("AvaliacaoAlunoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlunoID_aluno")
                        .HasColumnType("int");

                    b.Property<int>("AvaliacaoID_aluno")
                        .HasColumnType("int");

                    b.HasKey("AvaliacaoAlunoID");

                    b.HasIndex("AlunoID_aluno");

                    b.HasIndex("AvaliacaoID_aluno");

                    b.ToTable("AvaliacaoAluno");
                });

            modelBuilder.Entity("AprendaMais.Model.AvaliacaoPergunta", b =>
                {
                    b.Property<int>("AvaliacaoPerguntaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AvaliacaoID_aluno")
                        .HasColumnType("int");

                    b.Property<int?>("PerguntaID_disciplina")
                        .HasColumnType("int");

                    b.HasKey("AvaliacaoPerguntaID");

                    b.HasIndex("AvaliacaoID_aluno");

                    b.HasIndex("PerguntaID_disciplina");

                    b.ToTable("AvaliacaoPergunta");
                });

            modelBuilder.Entity("AprendaMais.Model.Dissertativa", b =>
                {
                    b.Property<int>("ID_pergunta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Resp_Aluno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gabarito1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gabarito2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gabarito3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_pergunta");

                    b.ToTable("Dissertativa");
                });

            modelBuilder.Entity("AprendaMais.Model.PerguntaDisciplina", b =>
                {
                    b.Property<int>("PerguntaDisciplinaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DisciplinaID_disciplina")
                        .HasColumnType("int");

                    b.Property<int?>("PerguntaID_disciplina")
                        .HasColumnType("int");

                    b.HasKey("PerguntaDisciplinaID");

                    b.HasIndex("DisciplinaID_disciplina");

                    b.HasIndex("PerguntaID_disciplina");

                    b.ToTable("PerguntaDisciplina");
                });

            modelBuilder.Entity("AprendaMais.Model.Texto", b =>
                {
                    b.Property<int>("ID_pergunta")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_pergunta")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ID_disciplina")
                        .HasColumnName("id_disciplina")
                        .HasColumnType("int");

                    b.Property<int>("ID_texto")
                        .HasColumnName("id_texto")
                        .HasColumnType("int");

                    b.Property<string>("texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_pergunta");

                    b.ToTable("texto");
                });

            modelBuilder.Entity("AprendaMais.Models.Aluno", b =>
                {
                    b.Property<int>("ID_aluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnName("nascimento")
                        .HasColumnType("date");

                    b.Property<int>("area")
                        .HasColumnType("int");

                    b.Property<string>("escola")
                        .IsRequired()
                        .HasColumnName("escola")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("sexo")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.HasKey("ID_aluno");

                    b.ToTable("aluno");
                });

            modelBuilder.Entity("AprendaMais.Models.Avaliacao", b =>
                {
                    b.Property<int>("ID_aluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_aluno")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ID_avaliacao")
                        .HasColumnName("id_avaliacao")
                        .HasColumnType("int");

                    b.Property<int>("ID_pergunta")
                        .HasColumnName("id_pergunta")
                        .HasColumnType("int");

                    b.Property<DateTime>("data")
                        .HasColumnName("dia")
                        .HasColumnType("date");

                    b.Property<int>("nota")
                        .HasColumnType("int");

                    b.HasKey("ID_aluno");

                    b.ToTable("avaliacao");
                });

            modelBuilder.Entity("AprendaMais.Models.Disciplina", b =>
                {
                    b.Property<int>("ID_disciplina")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_disciplina")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("ID_disciplina");

                    b.ToTable("disciplina");
                });

            modelBuilder.Entity("AprendaMais.Models.Pergunta", b =>
                {
                    b.Property<int>("ID_disciplina")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_disciplina")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Figura")
                        .HasColumnName("figura")
                        .HasColumnType("figure");

                    b.Property<int>("ID_alternativa")
                        .HasColumnName("id_alternativa")
                        .HasColumnType("int");

                    b.Property<int>("ID_pergunta")
                        .HasColumnName("id_pergunta")
                        .HasColumnType("int");

                    b.Property<int>("ID_universidade")
                        .HasColumnName("id_universidade")
                        .HasColumnType("int");

                    b.Property<bool>("dissertativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bool")
                        .HasDefaultValueSql("false");

                    b.Property<string>("enunciado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_disciplina");

                    b.ToTable("pergunta");
                });

            modelBuilder.Entity("AprendaMais.Models.Universidade", b =>
                {
                    b.Property<int>("ID_universidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_universidade")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("estado")
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(2)
                        .HasDefaultValue("SP");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("ID_universidade");

                    b.ToTable("universidade");
                });

            modelBuilder.Entity("AprendaMais.Model.AvaliacaoAluno", b =>
                {
                    b.HasOne("AprendaMais.Models.Aluno", "Aluno")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("AlunoID_aluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AprendaMais.Models.Avaliacao", "Avaliacao")
                        .WithMany("Alunos")
                        .HasForeignKey("AvaliacaoID_aluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AprendaMais.Model.AvaliacaoPergunta", b =>
                {
                    b.HasOne("AprendaMais.Models.Avaliacao", "Avaliacao")
                        .WithMany("Perguntas")
                        .HasForeignKey("AvaliacaoID_aluno");

                    b.HasOne("AprendaMais.Models.Pergunta", "Pergunta")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("PerguntaID_disciplina");
                });

            modelBuilder.Entity("AprendaMais.Model.PerguntaDisciplina", b =>
                {
                    b.HasOne("AprendaMais.Models.Disciplina", "Disciplina")
                        .WithMany("Perguntas")
                        .HasForeignKey("DisciplinaID_disciplina");

                    b.HasOne("AprendaMais.Models.Pergunta", "Pergunta")
                        .WithMany("Disciplinas")
                        .HasForeignKey("PerguntaID_disciplina");
                });
#pragma warning restore 612, 618
        }
    }
}
