// <auto-generated />
using System;
using AprendaMais.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AprendaMais.Migrations
{
    [DbContext(typeof(AprendaMaisContext))]
    partial class AprendaMaisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AprendaMais.Model.Pertence", b =>
                {
                    b.Property<int>("ID_texto")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_texto")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ID_pergunta")
                        .HasColumnName("id_pergunta");

                    b.HasKey("ID_texto");

                    b.HasAlternateKey("ID_pergunta");

                    b.ToTable("pertence");
                });

            modelBuilder.Entity("AprendaMais.Model.Texto", b =>
                {
                    b.Property<int>("ID_pergunta")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_pergunta")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnName("texto")
                        .HasColumnType("varchar(max)");

                    b.Property<int>("ID_disciplina")
                        .HasColumnName("id_disciplina");

                    b.Property<int>("ID_texto")
                        .HasColumnName("id_texto");

                    b.HasKey("ID_pergunta");

                    b.HasAlternateKey("ID_disciplina");


                    b.HasAlternateKey("ID_texto");

                    b.ToTable("texto");
                });

            modelBuilder.Entity("AprendaMais.Models.AlternativaProva", b =>
                {
                    b.Property<int>("ID_AlternativaProva")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_alternativaprova")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("A")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("B")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("C")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("D")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("E")
                        .HasColumnType("varchar(max)");

                    b.Property<int>("ID_pergunta")
                        .HasColumnName("id_pergunta");

                    b.Property<string>("Resp_correto")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)))
                        .HasColumnName("resp_certa")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnName("texto")
                        .HasColumnType("varchar(max)");

                    b.HasKey("ID_AlternativaProva");

                    b.ToTable("alternativaprova");
                });

            modelBuilder.Entity("AprendaMais.Models.Aluno", b =>
                {
                    b.Property<int>("ID_aluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnName("nascimento")
                        .HasColumnType("date");

                    b.Property<string>("Escola")
                        .IsRequired()
                        .HasColumnName("escola")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("area")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("sexo")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)))
                        .HasColumnType("varchar(1)");

                    b.HasKey("ID_aluno");

                    b.ToTable("aluno");
                });

            modelBuilder.Entity("AprendaMais.Models.Avaliacao", b =>
                {
                    b.Property<int>("ID_avaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_avaliacao")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ID_aluno")
                        .HasColumnName("id_aluno");

                    b.Property<DateTime>("data")
                        .HasColumnName("dia")
                        .HasColumnType("date");

                    b.Property<int>("nota");

                    b.HasKey("ID_avaliacao");

                    b.ToTable("avaliacao");
                });

            modelBuilder.Entity("AprendaMais.Models.Contem", b =>
                {
                    b.Property<int>("ID_avaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_avaliacao")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ID_pergunta")
                        .HasColumnName("id_pergunta");

                    b.HasKey("ID_avaliacao");

                    b.HasAlternateKey("ID_pergunta");

                    b.ToTable("contem");
                });

            modelBuilder.Entity("AprendaMais.Models.De", b =>
                {
                    b.Property<int>("ID_avaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_avaliacao")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ID_universidade")
                        .HasColumnName("ID_universidade");

                    b.HasKey("ID_avaliacao");

                    b.HasAlternateKey("ID_universidade");

                    b.ToTable("de");
                });

            modelBuilder.Entity("AprendaMais.Models.Disciplina", b =>
                {
                    b.Property<int>("ID_disciplina")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_disciplina")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("ID_disciplina");

                    b.ToTable("disciplina");
                });

            modelBuilder.Entity("AprendaMais.Models.Ede", b =>
                {
                    b.Property<int>("ID_universidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_universidade")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ID_pergunta")
                        .HasColumnName("id_pergunta");

                    b.HasKey("ID_universidade");

                    b.HasAlternateKey("ID_pergunta");

                    b.ToTable("ede");
                });

            modelBuilder.Entity("AprendaMais.Models.Faz", b =>
                {
                    b.Property<int>("ID_aluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_aluno")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ID_avaliacao")
                        .HasColumnName("id_avaliacao");

                    b.HasKey("ID_aluno");

                    b.HasAlternateKey("ID_avaliacao");

                    b.ToTable("faz");
                });

            modelBuilder.Entity("AprendaMais.Models.Pergunta", b =>
                {
                    b.Property<int>("ID_pergunta")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_pergunta")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Figura")
                        .HasColumnName("figura")
                        .HasColumnType("figure");

                    b.Property<int>("ID_disciplina")
                        .HasColumnName("id_disciplina");

                    b.Property<int>("ID_universidade")
                        .HasColumnName("id_universidade");

                    b.Property<string>("texto_pergunta")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.HasKey("ID_pergunta");

                    b.ToTable("pergunta");
                });

            modelBuilder.Entity("AprendaMais.Models.PerguntaProva", b =>
                {
                    b.Property<int>("ID_perguntaProva")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_perguntaprova")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ID_pergunta")
                        .HasColumnName("id_pergunta");

                    b.Property<int>("ID_prova")
                        .HasColumnName("id_prova");

                    b.HasKey("ID_perguntaProva");

                    b.ToTable("perguntaprova");
                });

            modelBuilder.Entity("AprendaMais.Models.Possui", b =>
                {
                    b.Property<int>("ID_pergunta")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_pergunta")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ID_perguntaProva")
                        .HasColumnName("id_perguntaprova");

                    b.HasKey("ID_pergunta");

                    b.HasAlternateKey("ID_perguntaProva");

                    b.ToTable("possui");
                });

            modelBuilder.Entity("AprendaMais.Models.Ser", b =>
                {
                    b.Property<int>("ID_pergunta")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_pergunta")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ID_disciplina")
                        .HasColumnName("id_disciplina");

                    b.HasKey("ID_pergunta");

                    b.HasAlternateKey("ID_disciplina");

                    b.ToTable("ser");
                });

            modelBuilder.Entity("AprendaMais.Models.Universidade", b =>
                {
                    b.Property<int>("ID_universidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_universidade")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("estado")
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(2)
                        .HasDefaultValue("SP");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("ID_universidade");

                    b.ToTable("universidade");
                });
#pragma warning restore 612, 618
        }
    }
}
